
const scenarios = {
  traffic: {q:'venture.example -> next_best_move?', STATE:'Site live; weak discoverability', NEXT:'Diagnose intent gaps and prepare a focused acquisition experiment', AUTH:'Recommend and prepare; entrepreneur approves publishing and spend', PROOF:'Qualified visits, engaged sessions, conversion event, cost guardrail', TTL:'7 days', conf:['illustrative','hypothesis','bounded','measurement','refresh']},
  idea: {q:'newventure.example -> launch_path?', STATE:'Idea is credible; online identity is not established', NEXT:'Resolve name, domain, launch narrative, and editable first presence', AUTH:'Generate options; entrepreneur chooses brand and commits launch', PROOF:'Domain activated, first page published, first customer action', TTL:'48 hours', conf:['illustrative','candidate model','human-led','observable','refresh']},
  service: {q:'service.example -> booking_momentum?', STATE:'Demand exists; booking and follow-up leak momentum', NEXT:'Simplify booking, prepare reminders, surface exceptions', AUTH:'Automate approved reminders; human handles sensitive exceptions', PROOF:'Booking completion, response latency, no-show trend', TTL:'72 hours', conf:['illustrative','candidate model','bounded','measurement','refresh']},
  seller: {q:'shop.example -> repeat_growth?', STATE:'Transactions occur; repeat behavior is uneven', NEXT:'Prepare a contextual re-engagement action with margin guardrails', AUTH:'Execute only within approved audience, channel, offer, and budget', PROOF:'Return visits, repeat conversion, margin, opt-out and complaint signals', TTL:'24 hours', conf:['illustrative','candidate model','bounded','measurement','refresh']}
};
function setScenario(name){const s=scenarios[name]; if(!s)return; document.querySelectorAll('.scenario-btn').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===name))); const q=document.querySelector('[data-query]'); if(q)q.firstChild.textContent=s.q+' '; ['STATE','NEXT','AUTH','PROOF','TTL'].forEach((k,i)=>{const el=document.querySelector(`[data-record="${k}"]`);if(el){el.querySelector('.record-val').textContent=s[k];el.querySelector('.record-conf').textContent=s.conf[i]}})}
document.addEventListener('click',e=>{const b=e.target.closest('.scenario-btn');if(b)setScenario(b.dataset.scenario); const tab=e.target.closest('.score-tab');if(tab){document.querySelectorAll('.score-tab').forEach(x=>x.setAttribute('aria-selected','false'));tab.setAttribute('aria-selected','true');const panel=document.querySelector('.score-panel');panel.innerHTML=tab.dataset.content}});
document.addEventListener('keydown',e=>{if(e.target.matches('.scenario-btn')&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){const bs=[...document.querySelectorAll('.scenario-btn')],i=bs.indexOf(e.target),n=(i+(e.key==='ArrowRight'?1:-1)+bs.length)%bs.length;bs[n].focus();setScenario(bs[n].dataset.scenario)}});
